from langchain_google_genai import ChatGoogleGenerativeAI
from dotenv import load_dotenv
import streamlit as st
from langchain_core.load import loads
import json

# ── Load environment variables from .env file ─────────────────────────────────
# GOOGLE_API_KEY must be set in your .env file
load_dotenv()

# ── Initialize Gemini Model ───────────────────────────────────────────────────
# gemini-2.5-flash-lite is a lightweight, fast, and cost-effective Gemini model
model = ChatGoogleGenerativeAI(model="gemini-2.5-flash-lite")

# ── Page Config ───────────────────────────────────────────────────────────────
# Sets the browser tab title, icon, and layout of the Streamlit app
st.set_page_config(
    page_title="Research Paper Summarizer",
    page_icon="📄",
    layout="centered"
)

# ── Header ────────────────────────────────────────────────────────────────────
# Displays the main title and a short description at the top of the page
st.title("Research Paper Summarizer")
st.caption("Summarize complex research papers in your preferred style and length.")
st.divider()

# ── Sidebar — User Preferences ────────────────────────────────────────────────
# All user inputs are placed in the sidebar to keep the main area clean
with st.sidebar:
    st.header("Configuration")
    st.info("Select your preferences and click Summarize to generate a summary.")

    # Dropdown to select which research paper to summarize
    paper_input = st.selectbox(
        "Research Paper",
        [
            "Attention Is All You Need",
            "BERT: Pre-training of Deep Bidirectional Transformers",
            "GPT-3: Language Models are Few-Shot Learners",
            "Diffusion Models Beat GANs on Image Synthesis",
        ]
    )

    # Dropdown to select the tone and style of the explanation
    style_input = st.selectbox(
        "Explanation Style",
        ["Beginner-Friendly", "Technical", "Code-Oriented", "Mathematical"]
    )

    # Dropdown to control how long the generated summary should be
    length_input = st.selectbox(
        "Explanation Length",
        ["Short (1-2 paragraphs)", "Medium (3-5 paragraphs)", "Long (detailed explanation)"]
    )

    # Button that triggers the summarization process when clicked
    summarize_btn = st.button("Summarize", use_container_width=True)

# ── Main Area — Display Selected Options ──────────────────────────────────────
# Shows the selected paper name as a subheader in the main content area
st.subheader(paper_input)

# Display selected style and length as metric cards for quick reference
col1, col2 = st.columns(2)
col1.metric("Style", style_input)
col2.metric("Length", length_input)
st.divider()

# ── Generation — Run Chain on Button Click ────────────────────────────────────
if summarize_btn:
    with st.spinner("Generating summary..."):
        try:
            # Load the prompt template from template.json
            # template.json is generated by running prompt_generator.py
            with open("template.json", "r") as f:
                template = loads(json.dumps(json.load(f)))

            # Build the LangChain pipeline: prompt template → Gemini model
            chain = template | model

            # Invoke the chain by passing the user's selected inputs
            # These fill in the placeholders in the prompt template
            result = chain.invoke({
                'paper_input': paper_input,
                'style_input': style_input,
                'length_input': length_input
            })

            # Display the generated summary to the user
            st.success("Summary generated successfully!")
            st.markdown("### Summary")
            st.write(result.content)

        except Exception as e:
            # Show a friendly error message if something goes wrong
            st.error(f"An error occurred: {e}")